# Generated by Django 5.1.2 on 2025-09-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchants', '0003_alter_merchant_latitude_alter_merchant_longitude'),
        ('products', '0002_backup_and_restructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='freshproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='freshproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantcategory'),
        ),
        migrations.AlterField(
            model_name='freshproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='freshproduct',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_products', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='prelovedproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='prelovedproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantcategory'),
        ),
        migrations.AlterField(
            model_name='prelovedproduct',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_products', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='readytoeatproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='readytoeatproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantcategory'),
        ),
        migrations.AlterField(
            model_name='readytoeatproduct',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_products', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantcategory'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_products', to='merchants.merchant'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['content_type', 'object_id'], name='product_ima_content_e2b269_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['content_type', 'object_id'], name='product_rev_content_4d3f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['content_type', 'object_id'], name='product_tag_content_2733a2_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['content_type', 'object_id'], name='product_var_content_b630f4_idx'),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
