# Generated by Django 5.1.2 on 2025-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_images_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshproduct',
            name='image_urls',
            field=models.JSONField(blank=True, help_text='Array of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='prelovedproduct',
            name='image_urls',
            field=models.JSONField(blank=True, help_text='Array of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='readytoeatproduct',
            name='image_urls',
            field=models.JSONField(blank=True, help_text='Array of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='image_urls',
            field=models.JSONField(blank=True, help_text='Array of image URLs', null=True),
        ),
    ]
