# Generated by Django 5.1.2 on 2025-09-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_images_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshproduct',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='prelovedproduct',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='readytoeatproduct',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='freshproduct',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='prelovedproduct',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='readytoeatproduct',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs', null=True),
        ),
    ]
