# Generated by Django 5.1.2 on 2025-09-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_merchant_latitude_alter_merchant_longitude'),
        ('products', '0005_add_images_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_brands', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Brand',
                'verbose_name_plural': 'Merchant Brands',
                'db_table': 'merchant_brands',
                'unique_together': {('merchant', 'brand_name')},
            },
        ),
    ]
