# Generated by Django 5.1.2 on 2025-09-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merchantbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantbrand'),
        ),
        migrations.AlterField(
            model_name='prelovedproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantbrand'),
        ),
        migrations.AlterField(
            model_name='readytoeatproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantbrand'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.merchantbrand'),
        ),
    ]
