# Generated by Django 5.1.2 on 2025-09-07 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_types', to='merchants.businesscategory')),
            ],
            options={
                'unique_together': {('business_category', 'business_type')},
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('merchant_host_id', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Frozen'), (3, 'Deleted'), (4, 'Unverified'), (5, 'Pending'), (6, 'Rejected')], default=4)),
                ('business_registration', models.IntegerField(choices=[(0, 'Registered (VAT Included)'), (1, 'Registered (NON-VAT)'), (2, 'Unregistered')], default=2)),
                ('phone', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('settlement_emails', models.JSONField(blank=True, default=list)),
                ('withdrawal_option', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.URLField(blank=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('documents_info', models.JSONField(blank=True, default=dict)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='merchants.businesscategory')),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='merchants.businesstype')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('file_url', models.URLField()),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_documents', to='merchants.merchant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webauth.admin')),
            ],
            options={
                'unique_together': {('merchant', 'document_type')},
            },
        ),
    ]
