# Generated by Django 5.1.2 on 2025-08-29 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Frozen'), (3, 'Deleted'), (4, 'Unverified')], default=0)),
                ('profile_picture', models.URLField(blank=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('merchant_host_id', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Frozen'), (3, 'Deleted'), (4, 'Unverified')], default=4)),
                ('business_registration', models.IntegerField(choices=[(0, 'Registered (VAT Included)'), (1, 'Registered (NON-VAT)'), (2, 'Unregistered')], default=2)),
                ('mcc', models.IntegerField(choices=[(0, 'Food Stall'), (1, 'Pre-loved'), (2, 'Fresh Market'), (3, 'Hardware'), (4, 'Grocery Store'), (5, 'Sari-Sari Store'), (6, 'Pharmacy'), (7, 'Online Seller'), (8, 'Bakery'), (9, 'Coffee Shop'), (10, 'Restaurant'), (11, 'Fast Food'), (12, 'Meat Shop'), (13, 'Fish Vendor'), (14, 'Street Food'), (15, 'Clothing/Apparel'), (16, 'Electronics'), (17, 'General Merchandise'), (18, 'Laundry Products'), (19, 'Water Refilling Station'), (20, 'Computer Shop'), (21, 'Appliance Store'), (22, 'Mobile Store'), (23, 'Pet Supplies'), (24, 'Motor Parts'), (25, 'Rice Retailer'), (26, 'Furniture'), (27, 'School Supplies'), (28, 'Vegetable & Fruit Vendor'), (29, 'Mall'), (30, 'Toy Store'), (31, 'Bookstore'), (32, 'Sporting Goods'), (33, 'Jewelry Store'), (34, 'Home Decor / Furnishing'), (35, 'Cosmetic & Beauty Products'), (36, 'Automotive Supplies'), (37, 'Baby Products')])),
                ('phone', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('settlement_emails', models.JSONField(blank=True, default=list)),
                ('withdrawal_option', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.URLField(blank=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('documents_info', models.JSONField(blank=True, default=dict)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Frozen'), (3, 'Deleted'), (4, 'Unverified')], default=4)),
                ('profile_picture', models.URLField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Frozen'), (3, 'Deleted'), (4, 'Unverified')], default=4)),
                ('profile_picture', models.URLField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('merchant_signup', 'Merchant Signup'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change')], max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'verified'], name='webauth_ema_email_03f2d8_idx'), models.Index(fields=['expires_at'], name='webauth_ema_expires_1a35f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('file_url', models.URLField()),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_documents', to='webauth.merchant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webauth.admin')),
            ],
            options={
                'unique_together': {('merchant', 'document_type')},
            },
        ),
    ]
