# Generated by Django 5.1.2 on 2025-08-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mcc', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MCC',
                'verbose_name_plural': 'MCCs',
                'db_table': 'mcc',
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_types', to='webauth.mcc')),
            ],
            options={
                'verbose_name': 'Business Type',
                'verbose_name_plural': 'Business Types',
                'db_table': 'business_type',
            },
        ),
        migrations.AlterUniqueTogether(
            name='businesstype',
            unique_together={('mcc', 'business_type')},
        ),
    ]
