# Generated by Django 5.1.2 on 2025-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0002_auto_20250831_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='webauth.mcc'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='webauth.businesstype'),
        ),
    ]
