# Generated by Django 5.1.2 on 2025-08-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0003_merchant_business_category_merchant_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='mcc',
            field=models.IntegerField(blank=True, choices=[(0, 'Food Stall'), (1, 'Pre-loved'), (2, 'Fresh Market'), (3, 'Hardware'), (4, 'Grocery Store'), (5, 'Sari-Sari Store'), (6, 'Pharmacy'), (7, 'Online Seller'), (8, 'Bakery'), (9, 'Coffee Shop'), (10, 'Restaurant'), (11, 'Fast Food'), (12, 'Meat Shop'), (13, 'Fish Vendor'), (14, 'Street Food'), (15, 'Clothing/Apparel'), (16, 'Electronics'), (17, 'General Merchandise'), (18, 'Laundry Products'), (19, 'Water Refilling Station'), (20, 'Computer Shop'), (21, 'Appliance Store'), (22, 'Mobile Store'), (23, 'Pet Supplies'), (24, 'Motor Parts'), (25, 'Rice Retailer'), (26, 'Furniture'), (27, 'School Supplies'), (28, 'Vegetable & Fruit Vendor'), (29, 'Mall'), (30, 'Toy Store'), (31, 'Bookstore'), (32, 'Sporting Goods'), (33, 'Jewelry Store'), (34, 'Home Decor / Furnishing'), (35, 'Cosmetic & Beauty Products'), (36, 'Automotive Supplies'), (37, 'Baby Products')], null=True),
        ),
    ]
