# Generated by Django 5.1.2 on 2025-08-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0004_make_mcc_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='mcc',
        ),
    ]
