# Generated by Django 5.1.2 on 2025-08-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0005_remove_old_mcc_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstype',
            old_name='mcc',
            new_name='business_category',
        ),
        migrations.AlterUniqueTogether(
            name='businesstype',
            unique_together={('business_category', 'business_type')},
        ),
    ]
