# Generated by Django 5.1.2 on 2025-08-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0006_rename_mcc_to_business_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Frozen'), (3, 'Deleted'), (4, 'Unverified'), (5, 'Pending')], default=4),
        ),
    ]
