# Generated by Django 5.1.2 on 2025-08-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0007_alter_merchant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Frozen'), (3, 'Deleted'), (4, 'Unverified'), (5, 'Pending'), (6, 'Rejected')], default=4),
        ),
    ]
